force-app/main/default/objects/Order_Return_c__c/Order_Return_c__c.object-meta.xml
<CustomObject>
    <label>order return</label>
    <nameField>
        <label>Order_Return__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>order returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Return_c__c/fields/Request_date__c.field-meta.xml
<CustomField>
    <fullName>Request_date__c</fullName>
    <label>Request date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Return_c__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReturnController.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : ReturnController
 * Author          : <YourName>
 * Created Date    : Apr 24, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Apr 24, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Apr 24, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class ReturnController {

	@AuraEnabled
	public static string  returnController(Order_Return_c__c req) {
		// duplicate check //
		List<Order_Return_c__c> existing = [select id from Order_Return_c__c where Order_Number__c = :req.Order_Number__c LIMIT 1];
		if(!existing.isEmpty()){
			return 'return already requested';
		}
		 // date validation //
		 if(date.today().daysBetween(req.Delivery_Date__c)>7){
			return 'return period expired';
		 }
		 // prepare data //
		 req.Request_date__c = date.today();
		 req.status__c = 'Requested';
		 insert req;
		 return 'success';
	}	

}